include:
  - path:
      - ./docker-compose-test.yml
      - ./docker/e2e.override.yml
services:
  e2e-tests:
    container_name: e2e-tests
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    ports:
      - 9323:9323
    depends_on:
      sqnc-matchmaker-api:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - LOG_LEVEL=debug
      - DB_HOST=postgres-matchmaker-api
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sqnc-matchmaker-api
      - IDENTITY_SERVICE_HOST=identity-service
      - IDENTITY_SERVICE_PORT=3000
      - NODE_HOST=node
      - NODE_PORT=9944
      - ENABLE_INDEXER=true
      - USER_URI=//Alice
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - WATCHER_POLL_PERIOD_MS=10000
      - WATCHER_TIMEOUT_MS=2000
      - INDEXER_TIMEOUT_MS=3000000
      - API_SWAGGER_BG_COLOR=#fafafa
      - API_SWAGGER_TITLE=MatchmakerAPI
      - API_SWAGGER_HEADING=MatchmakerAPI
      - IDP_CLIENT_ID=sequence
      - IDP_PUBLIC_URL_PREFIX=http://keycloak:8080/realms/member-a/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/member-a/protocol/openid-connect
      - IDP_TOKEN_PATH=/token
      - IDP_JWKS_PATH=/certs
      - LOAD_TESTS=true
