version: '3'

services:
  postgres-matchmaker-api:
    image: postgres:15.2-alpine
    container_name: postgres-matchmaker-api
    ports:
      - 5432:5432
    volumes:
      - matchmaker-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dscp-matchmaker-api
  
  postgres-identity-service:
    image: postgres:15.2-alpine
    container_name: postgres-identity
    ports:
      - 5433:5432
    volumes:
      - identity-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dscp-identity-service
  
  dscp-identity-service:
    image: digicatapult/dscp-identity-service:latest
    container_name: identity-service
    command: /bin/sh -c "
      sleep 30 &&
      npx knex migrate:latest &&
      node app/index.js"
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - API_HOST=dscp-node
      - DB_HOST=postgres-identity-service
      - DB_PORT=5432
      - DB_NAME=dscp-identity-service
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SELF_ADDRESS=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - AUTH_TYPE=${AUTH_TYPE:-NONE}

  dscp-node-alice:
    image: digicatapult/dscp-node:v8.0.0-bug_revert-aura
    container_name: alice
    command:
      --base-path /data/alice
      --chain local
      --alice
      --port 30333 
      --ws-port 9944 
      --rpc-port 9933 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure

  dscp-node-bob:
    image: digicatapult/dscp-node:v8.0.0-bug_revert-aura
    container_name: bob
    command:
      --base-path /data/bob
      --chain local
      --bob
      --port 30334 
      --ws-port 9945 
      --rpc-port 9934 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
      --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    ports:
      - 30334:30334
      - 9945:9945
      - 9934:9934
    restart: on-failure


  dscp-node-charlie:
    image: digicatapult/dscp-node:v8.0.0-bug_revert-aura
    container_name: charlie
    command:
      --base-path /data/charlie
      --chain local
      --charlie
      --port 30335 
      --ws-port 9946 
      --rpc-port 9934 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
      --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    ports:
      - 30335:30335
      - 9946:9946
      - 9935:9935
    restart: on-failure

  ipfs:
    image: ipfs/go-ipfs:v0.18.1
    container_name: ipfs
    environment:
      - |
        IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/
        /base16/
        0000000000000000000000000000000000000000000000000000000000000000
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
volumes:
  matchmaker-api-storage:
  identity-storage: